export const questions = [
    "Potato Chips & National Security",
    "Asteroids & Middle School Cafeterias",
    "Sunscreen & Ancient Egypt",
    "Ice Cream Flavors & Political Elections",
    "Shoelaces & The CIA",
    "Antique Furniture & Black Holes",
    "E-Sports Tournaments & Climate Change",
    "Fast-Food Mascots & The Federal Reserve",
    "Dental Hygiene & The Bermuda Triangle",
    "Fireworks & Alien Technology",
    "Rubber Ducks & Quantum Computers",
    "National Parks & Secret Societies",
    "Artificial Sweeteners & UFO Sightings",
    "Vitamins & Mind Control Experiments",
    "Bubble Wrap & Space Exploration",
    "The Eiffel Tower & Time Travel",
    "Horror Movies & Weather Forecasting",
    "Public Libraries & Cryptography",
    "Waffle Irons & Crop Circles",
    "Pandas & The Internet of Things",
    "Traffic Jams & Deep Sea Exploration",
    "Pet Food Brands & Famous Paintings",
    "Camping Gear & Ancient Greek Mythology",
    "Perfume & Economic Recessions",
    "Bowling Alleys & Extraterrestrial Life",
    "Art Museums & Genetic Modification",
    "Ski Resorts & Clandestine Spy Operations",
    "Bridges & Artificial Intelligence",
    "Eyeglasses & Surveillance Drones",
    "Breakfast Buffets & Conspiracy Theories",
    "Fashion Magazines & Cloning Facilities",
    "Jigsaw Puzzles & DNA Sequencing",
    "Board Games & Artificial Superintelligence",
    "The Color Blue & High-Speed Rail Projects",
    "Pineapples & Space Lasers",
    "Action Movies & Viral Memes",
    "Antique Clocks & Medical Breakthroughs",
    "Theme Parks & Ancient Manuscripts",
    "Self-Help Books & Parallel Universes",
    "Toothpaste Brands & Alien Abductions",
    "Wind Turbines & Cybersecurity",
    "Parking Meters & Hologram Technology",
    "Celebrity Pets & Astrophysics",
    "Hiking Trails & Reality TV Show Secrets",
    "Fast Fashion & National Monuments",
    "Paper Towels & Cyber Warfare",
    "Luxury Watches & Pyramid Schemes",
    "Tattoo Parlors & Biotechnology Labs",
    "Sandwiches & Historical Landmarks",
    "Sneakers & Cryptocurrency Scams",
    "Garden Gnomes & Nanotechnology",
    "Fruit Smoothies & Artificial Intelligence",
    "Bungee Jumping & Stock Market Predictions",
    "Carnivals & Scientific Research",
    "Fairy Tales & High Frequency Trading",
    "Electric Cars & Occult Practices",
    "Ice Skating & DNA Testing Kits",
    "Yoga Mats & Alternate Realities",
    "Social Media Challenges & Ancient Languages",
    "Streaming Platforms & Genetic Engineering",
    "Virtual Reality & Ancient Artifacts",
    "Pet Grooming & Hologram Technology",
    "Shampoo & Underwater Archeology",
    "Soup Recipes & Satellite Images",
    "Comic Book Stores & Interstellar Communication",
    "Pizza Delivery & DNA Mutation",
    "Renaissance Paintings & Internet Trolls",
    "Luxury Yachts & Government Experiments",
    "Roller Coasters & Facial Recognition Software",
    "Carnivorous Plants & Reality Shows",
    "Space Shuttles & Fashion Week",
    "VR Headsets & Rare Earth Minerals",
    "Hairstyles & Climate Change Conferences",
    "Traffic Cones & Quantum Computing",
    "Golf Courses & Secret Bunkers",
    "Meteor Showers & Chain Restaurants",
    "Wine Tasting & Nanobots",
    "Solar Panels & Magic Tricks",
    "Ballet & Space Missions",
    "Lip Balm & Artificial Intelligence",
    "Bicycles & Time Travel",
    "Tattoo Ink & Space Dust",
    "Birdwatching & Conspiracy Theories",
    "Balloons & Genetic Modification",
    "Drones & Antique Books",
    "Clouds & Cryptocurrency",
    "Beanbags & Government Experiments",
    "Submarines & Ancient Rituals",
    "Lava Lamps & Secret Agents",
    "Fishing Gear & Secret Codes",
    "Haunted Houses & Agricultural Subsidies",
    "Fitness Apps & Corporate Espionage",
    "Bowling Shoes & Artificial Sweeteners",
    "Space Stations & Art Installations",
    "Fidget Spinners & Financial Markets",
    "Seashells & Surveillance Satellites",
    "Ancient Ruins & Fast Food Apps",
    "Erasers & Astronomical Events",
    "Volcanoes & Reality TV Stars",
    "Table Tennis & Nuclear Physics",
    "Origami & Social Media Algorithms",
    "Robotic Vacuums & Cryptography",
    "Ghost Stories & Particle Physics",
    "Kites & Government Funding",
    "Astrology Apps & Big Data",
    "Ski Goggles & Public Speaking",
    "Face Masks & Celebrity Scandals",
    "Karaoke & Global Warming",
    "Microphones & Lunar Phases",
    "Honey Bees & Blockchain",
    "Fairy Tales & Video Streaming Services",
    "Matchsticks & AI Ethics",
    "Riddles & Supercomputers",
    "Soccer Matches & Genetic Codes",
    "Milkshakes & Theoretical Physics",
    "Bird Feeders & Tax Evasion",
    "Newspapers & Cyber Attacks",
    "Mannequins & Astrobiology",
    "Chewing Gum & Digital Security",
    "Gummy Bears & Climate Policy",
    "Board Games & Space Tourism",
    "Censorship & Fast Food Advertisements",
  "Social Media Platforms & Political Bias",
  "Pharmaceutical Companies & Beauty Standards",
  "Privacy Laws & Celebrity Scandals",
  "Media Outlets & War Propaganda",
  "Luxury Fashion Brands & Income Inequality",
  "Genetic Testing & Crime Predictors",
  "Political Campaigns & Reality TV Ratings",
  "Healthcare Costs & Fast Food Chains",
  "Social Media Algorithms & Mental Health",
  "Religion & Multinational Corporations",
  "Vaccine Patents & Stock Market Crashes",
  "Advertising Industry & Addiction",
  "Reality TV & Plastic Surgery Trends",
  "Food Shortages & Wealth Inequality",
  "Lobbyists & Environmental Policies",
  "Political Scandals & Cryptocurrency",
  "Public Health Studies & Junk Food",
  "Surveillance Technology & Public Protests",
  "Private Schools & Government Funding",
  "International Aid & Corrupt Governments",
  "Diet Fads & Body Image Issues",
  "Drug Laws & Corporate Profits",
  "Environmental Disasters & Oil Companies",
  "Artificial Intelligence & Job Market",
  "Internet Privacy & Government Surveillance",
  "Social Movements & Fashion Trends",
  "Military Funding & Celebrity Endorsements",
  "Conspiracy Theorists & Media Ratings",
  "Plastic Pollution & Major Corporations",
  "Corporate Tax Loopholes & Infrastructure",
  "Immigration Policy & Labor Markets",
  "Media Bias & Political Campaign Funding",
  "Cybersecurity Breaches & Stock Prices",
  "Mental Health Apps & Data Privacy",
  "Pandemic & Corporate Profits",
  "Celebrity Marriages & Reality Shows",
  "Agriculture Subsidies & Processed Foods",
  "Public Schools & Standardized Testing",
  "Internet Trolls & Political Propaganda",
  "Government Budgets & Welfare Programs",
  "Food Stamps & Pharmaceutical Companies",
  "Technology Companies & Human Rights",
  "Reality TV & Criminal Justice System",
  "Billionaire Philanthropy & Tax Evasion",
  "Space Tourism & Environmental Harm",
  "Climate Change Denial & Oil Lobbyists",
  "Government Bailouts & Stock Buybacks",
  "Voting Systems & Corporate Interests",
  "Music Industry & Political Movements",
  "Social Media Challenges & Self-Esteem",
  "Opioid Crisis & Healthcare Lobbyists",
  "Religion & Tax Breaks",
  "Prison System & Fast Food Contracts",
  "Social Media Influencers & False Advertising",
  "Prescription Drug Prices & Political Campaigns",
  "Prison Labor & Clothing Brands",
  "Election Fraud & Media Bias",
  "Fossil Fuels & Climate Agreements",
  "Fast Fashion & Child Labor",
  "Video Game Violence & Youth Behavior",
  "Higher Education & Student Debt",
  "Social Media & Conspiracy Theories",
  "Drug Addiction & Private Rehab Centers",
  "Real Estate Prices & Gentrification",
  "Data Collection & Political Campaigns",
  "Online Shopping & Brick-and-Mortar Stores",
  "Mental Health Issues & Social Media",
  "Pandemic Response & Pharmaceutical Profits",
  "Social Welfare & Tax Policies",
  "Big Tech & Privacy Invasion",
  "Healthcare Insurance & Political Lobbying",
  "Public Transit & Real Estate",
  "Athlete Endorsements & Political Activism",
  "Private Prisons & Crime Rates",
  "Education Funding & School Lunch Programs",
  "Social Media & Political Manipulation",
  "Voting Rights & Corporate Influence",
  "Climate Activism & Corporate Greenwashing",
  "Food Labeling & Government Regulation",
  "Pharmaceutical Patents & Generic Drugs",
  "Income Inequality & Tax Cuts",
  "Public Transport & Urban Development",
  "Alcohol Sales & Public Health Initiatives",
  "Influencer Marketing & Body Image",
  "Celebrity Culture & Mental Health",
  "Genetic Research & Biotech Companies",
  "International Relations & Arms Sales",
  "Elections & Media Ownership",
  "Trade Agreements & Environmental Standards",
  "Privacy Policies & Data Exploitation",
  "Political Scandals & Media Blackouts",
  "Space Exploration & Corporate Sponsorships",
  "Banking System & Economic Crashes",
  "Insurance Policies & Natural Disasters",
  "Agricultural Subsidies & Obesity Rates",
  "Tourism Industry & Environmental Damage",
  "Celebrities & Political Campaigns",
  "Housing Crisis & Real Estate Developers",
  "Streaming Platforms & Mental Health",
  "Food Deserts & Health Disparities",
  "Political Fundraising & Tax Havens",
  "Corporate Mergers & Job Losses",
  "Obesity & Processed Foods",
  "Labor Rights & Automation",
  "Corporate Monopolies & Small Businesses",
  "Mental Health & Pharmaceutical Industry",
  "Plastic Production & Recycling Programs",
  "Political Donations & Lobbying Power",
  "Public Parks & Housing Developers",
  "Food Delivery Apps & Restaurant Industry",
  "Airline Regulations & Safety Standards",
  "E-Commerce & Traditional Retail",
  "Artificial Intelligence & Surveillance",
  "Military Spending & Civilian Projects",
  "Charitable Donations & Tax Evasion",
  "Economic Sanctions & Trade Agreements",
  "Water Shortages & Corporations",
  "Mental Health Stigma & Social Media",
  "Pandemic Policies & Economic Recovery"
];
  