export const questions = [
    "Time travel & government secrets",
    "Aliens & climate change",
    "Mind control & fast food",
    "The moon landing & secret societies",
    "Social media & psychological manipulation",
    "Cryptocurrency & global banking",
    "Bigfoot & the tech industry",
    "Artificial intelligence & personal privacy",
    "Vaccines & population control",
    "The Bermuda Triangle & advanced technology",
    "Mermaids & oceanic research",
    "Global warming & fossil fuel companies",
    "Haunted houses & real estate trends",
    "Robots & the future of humanity",
    "Ancient civilizations & modern architecture",
    "The internet & surveillance states",
    "The pyramids & extraterrestrial life",
    "Food additives & health conspiracies",
    "Astrology & financial markets",
    "Climate engineering & natural disasters",
    "The pharmaceutical industry & holistic medicine",
    "Genetic engineering & endangered species",
    "Space exploration & military technology",
    "Psychic abilities & the human brain",
    "The Titanic & hidden treasures",
    "Conspiracy theories & public education",
    "Doppelgängers & identity theft",
    "Secret codes & the history of language",
    "Elders of Zion & modern politics",
    "Corporate espionage & innovation",
    "Crop circles & ancient astronaut theories",
    "Alternative energy & big oil",
    "Reality TV & societal norms",
    "Climate activists & government agendas",
    "Virtual reality & human experience",
    "The Great Wall of China & global defense",
    "Fashion trends & cultural appropriation",
    "Quantum physics & spiritual awakening",
    "Superheroes & government propaganda",
    "Surveillance technology & civil liberties",
    "Ghosts & historical revisionism",
    "The Loch Ness Monster & ecological balance",
    "The internet of things & consumerism",
    "Animal testing & ethical dilemmas",
    "Urban legends & cultural folklore",
    "The power of music & social change",
    "Charity organizations & hidden motives",
    "Astrobiology & the search for truth",
    "Nostradamus & modern politics",
    "Lost civilizations & technology advancements",
    "Remote viewing & military strategy",
    "Telepathy & communication technology",
    "The Flat Earth theory & space exploration",
    "Artificial sweeteners & public health",
    "Shapeshifters & celebrity culture",
    "Area 51 & UFO sightings",
    "Cults & social media influence",
    "Historical figures & secret identities",
    "The placebo effect & medical research",
    "Endangered species & biodiversity loss",
    "Ancient prophecies & current events",
    "Television shows & societal behavior",
    "The Illuminati & major world events",
    "Climate refugees & international politics",
    "Hidden messages & advertising",
    "Smartphones & attention spans",
    "Pyramids & the power of belief",
    "Time loops & historical events",
    "Bioweapons & international relations",
    "Zodiac signs & personality traits",
    "Mysterious artifacts & archaeological discoveries",
    "Drones & privacy invasion",
    "The Sphinx & astronomical alignments",
    "Secret societies & the art world",
    "Global pandemics & government response",
    "Music industry & mind control",
    "Astrology & the stock market",
    "Fictional characters & real-life psychology",
    "Ancient manuscripts & modern science",
    "Martial arts & self-defense training",
    "Pseudoscience & mainstream media",
    "Ghost hunting & paranormal research",
    "Esoteric knowledge & religious beliefs",
    "War tactics & media coverage",
    "Reality manipulation & virtual environments",
    "Medical anomalies & conspiracy theories",
    "Chemtrails & weather patterns",
    "Space debris & environmental concerns",
    "The paranormal & scientific exploration",
    "Secret codes & espionage",
    "Environmental disasters & corporate interests",
    "Artificial intelligence & the future of work",
    "Quantum entanglement & consciousness",
    "Fashion icons & cultural movements",
    "Sasquatch & environmental conservation",
    "The Great Pyramid & the afterlife",
    "Psychic phenomena & brain function",
    "Urban legends & real-world events",
    "Historical conspiracies & modern media",
    "Artificial intelligence & human creativity",
    "Dinosaurs & extinction theories",
    "Phantom time hypothesis & historical accuracy",
    "Druidic practices & modern spirituality",
    "The Bermuda Triangle & international shipping",
    "The Fountain of Youth & modern medicine",
    "Biometric surveillance & civil rights",
    "The Yeti & climate change",
    "Genetic mutations & evolution",
    "Futurism & societal expectations",
    "Secret agents & espionage in history",
    "The impact of literature on society & propaganda",
    "The hidden meanings in fairy tales & societal norms",
    "Dream interpretation & psychological health",
    "The role of women in ancient societies & modern feminism",
    "Myths & the formation of cultural identity",
    "Philosophy & the nature of reality",
    "Social movements & political change",
    "Artificial ecosystems & climate manipulation",
    "Digital footprints & privacy invasion",
    "Cannibalism & survival instincts",
    "Historical accuracy in film & public perception",
    "Mindfulness & corporate America",
    "The power of branding & consumer behavior",
    "Conservation efforts & big corporations",
    "Lost treasures & adventurous quests",
    "Nuclear energy & environmental policy",
    "Superstitions & their origins",
    "The role of sports in society & nationalism",
    "Celebrity endorsements & consumer trust",
    "Decoding symbols in advertising & persuasion",
    "The influence of architecture on society & power",
    "Mysterious disappearances & urban exploration",
    "Historical figures & their hidden agendas",
    "Censorship & freedom of speech",
    "Elders of the Internet & youth culture",
    "The influence of ancient religions on modern beliefs"
];
