export const questions = [
    "People who leave shopping carts in the middle of the aisle",
    "The existence of glitter",
    "Why socks always go missing in the laundry",
    "People who don’t use turn signals",
    "The sound of people chewing loudly",
    "How autocorrect always messes up the most important words",
    "Why phone batteries never last as long as they should",
    "People who talk during movies",
    "Why everything needs a subscription now",
    "The struggle of opening plastic packaging",
    "People who stand too close in line",
    "The endless amount of streaming services",
    "How weather apps are always wrong",
    "Restaurant menus with too many options",
    "Why every app wants to send notifications",
    "The price of printer ink",
    "Getting a tangled mess of headphones",
    "People who stop in the middle of the sidewalk",
    "How Wi-Fi never reaches every corner of the house",
    "When toast lands butter-side down",
    "The unnecessary 15 variations of toothpaste",
    "Why everyone seems to talk on speakerphone in public",
    "The mystery of pens disappearing",
    "People who drive just under the speed limit",
    "When elevators stop at every floor",
    "The endless loading screens on streaming platforms",
    "People who clip their nails in public places",
    "When autocorrect changes 'yes' to 'yesterday'",
    "Why 'smart' fridges even exist",
    "Socks with holes in them",
    "How everything is so much more expensive now",
    "People who don't clean up after their pets",
    "The mystery of every remote button doing nothing",
    "How receipts are a mile long for one item",
    "How ketchup packets are impossible to open",
    "Unskippable ads on videos",
    "Coffee cups that aren’t properly insulated",
    "How earbuds always tangle, no matter what",
    "The invasion of glitter in every craft store",
    "Phone numbers that start with 'unknown caller'",
    "How people are always 'out of office' when you need them",
    "People who always take the biggest slice of pizza",
    "How single socks keep going missing",
    "Why there’s never enough dressing in a salad kit",
    "The absurdity of daylight saving time",
    "People who overshare on social media",
    "The mysterious drawer full of ketchup packets",
    "The frustration of trying to open a bag of chips",
    "Why hotel pillows are either too hard or too soft",
    "When people use all caps in emails",
    "The endless phone updates for no reason",
    "Why popcorn burns so easily in the microwave",
    "How auto-play always picks the worst next video",
    "The struggle to find matching Tupperware lids",
    "Why receipts fade even when you keep them safe",
    "How everyone gets sick on weekends",
    "When headphones get stuck in your hair",
    "People who always finish the coffee but never make more",
    "How freezer bags never keep things fresh",
    "How gas prices change every day",
    "The pain of walking on Legos",
    "Why hot chocolate is never hot enough",
    "People who don’t hold the door open",
    "Why sticky notes never stick",
    "When socks slip inside your shoes",
    "People who don’t pick up their phone",
    "The constant beeping of delivery trucks",
    "Why toothpaste always leaks from the cap",
    "How keyboards collect crumbs",
    "People who say 'we need to talk' without context",
    "Why printers never work when you need them",
    "The horror of lukewarm coffee",
    "When autocorrect changes 'okay' to 'Oklahoma'",
    "How Wi-Fi passwords are always a million characters",
    "The mystery of tangled holiday lights",
    "Why eggs always crack when you don’t want them to",
    "The never-ending search for phone chargers",
    "When the volume of ads is ten times louder",
    "Why ice cubes always stick together",
    "The annoyance of people talking on speakerphone in public",
    "Why blankets are never long enough",
    "People who always skip their turn in group games",
    "When milk expires the day you buy it",
    "The endless dings from email notifications",
    "How paper towels tear unevenly",
    "When rain starts right after you wash your car",
    "The confusion of too many coffee choices",
    "Why nobody fills up the water pitcher",
    "How autocorrect changes 'lol' to 'LOL'",
    "When the remote is always missing",
    "How food delivery apps are never on time",
    "Why everyone loves pineapple on pizza",
    "The struggle of untangling fairy lights",
    "The mystery of vanishing hair ties",
    "How public bathrooms are always out of soap",
    "People who always leave crumbs everywhere",
    "The eternal loop of 'forgot password'",
    "People who wear sunglasses indoors",
    "How there’s always traffic when you’re in a hurry",
    "The mystery of disappearing bobby pins",
    "When there’s only one checkout lane open",
    "People who press the elevator button multiple times",
    "The pointless length of waiting on hold",
    "When you can’t find the scissors even though you put them away",
    "Why bananas go from green to brown instantly",
    "People who always use speakerphone in public",
    "Why paper cuts hurt way more than they should",
    "How air travel always takes longer than planned",
    "When people put empty boxes back in the pantry",
    "The struggle of peeling off price stickers",
    "Why hot dogs and buns never come in matching quantities",
    "The endless amount of dust on electronics",
    "How soap bars always slip out of your hands",
    "People who leave time on the microwave",
    "The madness of unrolling cling wrap",
    "Why fast food isn’t actually fast",
    "How autocorrect never gets names right",
    "People who don’t clean the lint trap in dryers",
    "How cashiers ask if you want the receipt and then throw it away",
    "When every pen in the house decides to stop working",
    "People who don’t return their shopping cart",
    "The never-ending notifications on phones",
    "How ice cream always drips down the cone",
    "People who leave lids off containers",
    "When ads interrupt your favorite song",
    "The battle of trying to open a sealed plastic bag",
    "Why there’s always a fly in the kitchen",
    "When the Wi-Fi cuts out at the worst time",
    "Why clothes always wrinkle after ironing",
    "The mystery of socks going missing in the wash",
    "How people send texts in multiple bursts",
    "The pain of stubbing your toe on furniture",
    "Why voicemail even still exists",
    "When your favorite snacks are always out of stock",
    "How toothbrush bristles always bend out of shape",
    "Why chargers break so easily",
    "The sound of nails on a chalkboard",
    "Why people overshare on social media",
    "How alarm clocks always feel louder in the morning",
    "When dishes are ‘soaked’ instead of washed",
    "The hassle of untangling phone cables",
    "How pens explode at the worst times",
    "People who leave dishes in the sink",
    "The never-ending chain of update reminders",
    "How popcorn always burns in the microwave",
    "When all your friends cancel plans last minute",
    "People who text and walk at the same time",
    "The horror of finding glitter on everything",
    "The chaos of tangled Christmas lights",
    "People who let their dog bark all night",
    "Why pants always rip at the knees",
    "The torture of cold bathroom floors",
    "When your phone dies just before you reach home",
    "How coffee always drips onto your clothes",
    "People who never say ‘thank you’",
    "The struggle to find anything in the junk drawer",
    "Why people can’t park straight",
    "The frustration of low battery notifications",
    "Why spam emails keep coming no matter what",
    "The mystery of vanishing phone chargers",
    "People who chew with their mouths open",
    "How umbrellas always break during the first storm",
    "People who leave voicemail messages",
    "The mess of melted chocolate in pockets",
    "How your favorite jeans always rip",
    "When people drive under the speed limit",
    "How easy it is to lose chapstick",
    "The struggle of folding fitted sheets",
    "Why cereal bags are always impossible to open cleanly",
    "People who speak in baby voices to adults",
    "When people blast music in quiet places",
    "The annoyance of hangnails",
    "When your favorite show ends on a cliffhanger",
    "How leftovers always leak in the bag",
    "The endless apps that need updating",
    "When the lid won’t come off the jar",
    "How clothes get lost at the dry cleaners",
    "People who take forever at ATMs",
    "The struggle of finding matching socks",
    "How pens are never where you left them",
    "People who don’t rinse out their coffee cups",
    "When toothpaste squeezes out unevenly",
    "The annoyance of sticky elevator buttons",
    "How shopping carts never go in a straight line",
    "The challenge of opening a new pickle jar",
    "How receipts fade before you even read them",
    "Why remotes have way too many buttons",
    "The mystery of socks that go missing in the dryer",
    "How headphones always get tangled",
    "When shoes squeak in quiet places",
    "The challenge of carrying a hot coffee cup",
    "How bugs always find their way inside",
    "People who forget to mute on video calls",
    "When you spill coffee right after making it",
    "Why leftovers never taste the same",
    "How door handles get loose so quickly",
    "The chaos of group text notifications",
    "How laundry always piles up quickly",
    "The constant updates on every device",
    "Why everyone has allergies these days",
    "When shampoo bottles are almost impossible to open"
];
