export const questions = [
    "What if the internet was banned globally tomorrow?",
    "What if only the wealthy could access medical care?",
    "What if social media platforms were outlawed worldwide?",
    "What if all major governments united under one world government?",
    "What if everyone had to reveal their entire search history publicly?",
    "What if animals were granted the same legal rights as humans?",
    "What if all education was replaced with virtual reality learning?",
    "What if aliens made first contact and claimed Earth as their property?",
    "What if religion was outlawed and spiritual practice was banned?",
    "What if all criminal records became public information?",
    "What if people had to undergo a psychological test to become parents?",
    "What if immortality was possible, but only for the wealthy?",
    "What if everyone could read each other’s minds?",
    "What if the concept of gender was abolished entirely?",
    "What if poverty was punishable by exile from cities?",
    "What if there was a maximum income limit worldwide?",
    "What if every crime committed had to be broadcast live?",
    "What if humans had to live underground due to extreme weather?",
    "What if climate change was solved but all fossil fuels were banned?",
    "What if celebrities were forced to serve mandatory public service?",
    "What if government surveillance was mandatory in all homes?",
    "What if voting was illegal and leaders were chosen by lottery?",
    "What if marriage and family structures were government-controlled?",
    "What if physical books were banned in favor of digital media only?",
    "What if all energy was free but rationed by an authoritarian regime?",
    "What if everyone was born with a predetermined job they couldn’t change?",
    "What if all national borders were erased?",
    "What if high school diplomas became irrelevant and everyone had to attend trade school?",
    "What if everyone had a government-assigned social score that determined privileges?",
    "What if anyone could challenge someone else to a public duel legally?",
    "What if every person received a basic income but had no right to private property?",
    "What if every human had to work one day in prison each year?",
    "What if all entertainment had to be government-approved for moral content?",
    "What if scientists discovered a way to control emotions?",
    "What if physical exercise became mandatory for every citizen?",
    "What if life expectancy was capped at 60 by law?",
    "What if everyone’s life choices were determined by artificial intelligence?",
    "What if all food had to be vegetarian by law?",
    "What if holidays were banned, and every day was a workday?",
    "What if personal vehicles were outlawed and only public transport existed?",
    "What if friendships and relationships had to be licensed by the state?",
    "What if everyone had to serve five years in a random country?",
    "What if privacy was declared illegal worldwide?",
    "What if voting rights were restricted to only certain professions?",
    "What if all children were raised by the state until adulthood?",
    "What if all phone calls were public and recorded?",
    "What if the use of cash was outlawed, and only digital payments were allowed?",
    "What if everyone was required to move to a different country every five years?",
    "What if every person could be called for random psychological testing by the government?",
    "What if schools and universities were replaced by online learning centers only?",
    "What if everyone was required to wear a government-assigned uniform?",
    "What if history books were rewritten every decade?",
    "What if governments had the power to approve or deny marriages?",
    "What if dating apps were banned, and only arranged marriages were allowed?",
    "What if we could no longer live past 50 without a health test every year?",
    "What if everyone had to pass a yearly IQ test to retain citizenship rights?",
    "What if everyone had to broadcast their daily routines live on the internet?",
    "What if all forms of traditional medicine were outlawed?",
    "What if political parties were banned and leaders were chosen by random lottery?",
    "What if every job had a maximum salary, regardless of industry?",
    "What if all children were educated solely through AI and robotics?",
    "What if the oceans were completely restricted, and no one could go near them?",
    "What if everyone’s genetic information was publicly available?",
    "What if all art had to be government-approved?",
    "What if every home had to host a government representative once a year?",
    "What if humans had to live in designated sectors without free movement?",
    "What if friendships were illegal and everyone had to live independently?",
    "What if we could never speak directly to another person in real-time?",
    "What if sleep was regulated, and all citizens had to sleep during designated hours?",
    "What if memory modification technology existed and was widely used?",
    "What if marriage contracts were limited to 10 years by law?",
    "What if professional sports were banned?",
    "What if pets were illegal?",
    "What if any lie told was instantly known by everyone who heard it?",
    "What if every human had to be part of a social contract, outlining behavior for society?",
    "What if children chose their parents at birth?",
    "What if countries were divided into zones where only certain beliefs were allowed?",
    "What if all religions were consolidated into one global faith?",
  "What if everyone was required to take a drug that suppressed emotions?",
  "What if death penalties were replaced with lifelong forced labor?",
  "What if public shaming was legal as a form of punishment?",
  "What if laws allowed corporations to own individual people as employees for life?",
  "What if every crime had a minimum sentence of life in prison?",
  "What if everyone was required to have a government-monitored implant?",
  "What if human cloning was legal for the wealthy only?",
  "What if all voting rights were based on intelligence tests?",
  "What if only the top 10% of income earners could have children?",
  "What if anyone over 70 was required to undergo euthanasia?",
  "What if the internet was censored, and only 'approved' information was allowed?",
  "What if political opposition was illegal, and only one party existed worldwide?",
  "What if privacy was permanently banned, and all actions were recorded?",
  "What if organ selling was legalized, creating a market for body parts?",
  "What if every household was required to house a government spy?",
  "What if poverty was criminalized, and the homeless were put in camps?",
  "What if violent sports were legal and televised as entertainment?",
  "What if marriage was abolished, and the state assigned partners?",
  "What if freedom of speech was restricted to state-approved topics?",
  "What if a global DNA registry monitored and controlled genetic diversity?",
  "What if society operated under a survival-of-the-fittest law with no aid for the vulnerable?",
  "What if having more than one child was punishable by law?",
  "What if government ID was required to access the internet?",
  "What if certain professions were banned for specific genders?",
  "What if all debts were inherited across generations?",
  "What if criminal convictions resulted in lifelong bans from reproduction?",
  "What if speaking negatively about the government was punishable by death?",
  "What if body modification and plastic surgery were mandatory to conform to societal ideals?",
  "What if all art was banned as a form of 'distraction'?",
  "What if natural birth was illegal, and all babies were born in labs?",
  "What if the state chose every citizen's career based on a personality test?",
  "What if children belonged to the state until they turned 18?",
  "What if public displays of wealth were illegal and punishable?",
  "What if historical facts could be changed legally, rewriting history as needed?",
  "What if every person’s salary was publicly available and mandated by the government?",
  "What if a global organization tracked and controlled human population levels by law?",
  "What if expressing emotions in public was banned?",
  "What if people were required to 'pay' for life expectancy with hard labor?",
  "What if personal relationships required official government approval?",
  "What if people were ranked by 'value to society,' and privileges were assigned accordingly?",
  "What if unemployment was punishable by forced community service?",
  "What if alcohol and drugs were mandatory in certain situations to 'calm' society?",
  "What if all citizens over a certain age had to relinquish their assets to the state?",
  "What if college degrees were eliminated, and education was based only on 'aptitude'?",
  "What if anyone who disagreed with a state official was subject to exile?",
  "What if the government tracked and rated every citizen’s online activity?",
  "What if prisons became entirely private, profit-driven corporations?",
  "What if friendships and romantic relationships were based on social score compatibility?",
  "What if only people who passed a government-determined 'fitness' test could work?",
  "What if all freedoms could be 'bought back' at a high cost?",
  "What if global language was mandated, banning all native languages?",
  "What if birth control was illegal and childbearing was mandated?",
  "What if wealth was legally confiscated after death, with no inheritance allowed?",
  "What if dissent was treated as a mental illness and 'cured' with mandatory therapy?",
  "What if healthcare was based on social status and profession?",
  "What if extreme overpopulation led to mandatory population 'redistribution' zones?",
  "What if a ‘happiness police’ monitored moods, requiring corrective actions?",
  "What if emotions were regulated, and sadness was criminalized?",
  "What if people could only consume media approved by the government?",
  "What if public access to all libraries was restricted, with book approval needed to borrow?",
  "What if long-term relationships required an official 'renewal' every year?",
  "What if all private land ownership was banned, and everything was rented from the government?",
  "What if family units were abolished, and everyone was raised communally?",
  "What if every person had a maximum income level and the excess was taken by the state?",
  "What if people could only live in 'zones' based on socioeconomic status?",
  "What if sharing ideas outside of work hours was prohibited?",
  "What if high achievers were relocated to exclusive zones, separating them from the rest?",
  "What if sleep times were scheduled and mandated by the government?",
  "What if people had to compete for resources in a survival-based society?",
  "What if certain foods were outlawed, and only 'government-approved' meals existed?",
  "What if age-based discrimination was legal and enforced for societal ‘efficiency’?",
  "What if the government managed every individual’s health decisions?",
  "What if childhood was limited to specific government-controlled activities only?",
  "What if the elderly were required to ‘pass’ a usefulness test to retain rights?",
  "What if life-saving medical procedures were based on a person’s wealth alone?",
  "What if everyone was implanted with a device to monitor compliance with laws?",
  "What if universities were abolished and only on-the-job training was allowed?",
  "What if all public holidays were canceled in favor of continuous work cycles?",
  "What if high social score grants were necessary to access transportation and travel?",
  "What if empathy was artificially suppressed to increase 'productivity'?",
  "What if only people without any criminal record could use public resources?",
  "What if brain implants for controlled learning were mandatory in education?",
  "What if personal beliefs were required to be publicly declared for inspection?",
  "What if birth was regulated based on economic forecasts?",
  "What if retirement was banned and everyone had to work until they were incapacitated?",
  "What if accessing knowledge beyond basic literacy was forbidden without a permit?"
  ];
  