export const questions = [
    "What's your favorite movie of all time?",
    "Given the chance to have dinner with any three individuals, whether alive or deceased, who would you choose?",
    "What's the best vacation you've ever had?",
    "If you could have any superpower, what would it be and why?",
    "What's your favorite book or author?",
    "What's the most interesting place you've ever visited?",
    "What hobby have you always wanted to pick up?",
    "What's your go-to comfort food?",
    "What's a fun fact about you that not many people know?",
    "If you could learn any language fluently, which would it be?",
    "Have you ever had to break up with a friend? What was the reason?",
    "Who is one influential figure you wish you could make a hundred clones of?",
    "When you were a child, how did you imagine adulthood and how does that compare to reality?",
    "Who and what should you never be trapped with inside an elevator?",
    "What would detectives assume about you if they inspected your room without ever meeting you?",
    "If you became earth's official tour guide to aliens, where would you take them?",
    "Given an unlimited budget, how would you plan your own funeral?",
    "If every human came with a warning label, what would yours say?",
    "Imagine if your daily routine had been turned into a reality show. Which parts would be the most talked about?",
    "Who was the coolest kid in your high school and where is he/she now?",
    "Would you rather go to jail for a murder you never committed or kill someone and never get caught?",
    "What is one phrase you wish you could ban from everyone's vocabulary?",
    "What flaws would you be okay with in a romantic partner?",
    "How well would you get along with someone exactly like you?",
    "What is one weird belief you used to have when you were a kid?",
    "If you could be born in another era in history, which would you choose?",
    "If everyone had to decide on their career path at age six, what would your life look like now?",
    "Fill in the blank: 'When I am angry, I tend to ____.",
    "What superpowers are probably more inconvenient than they are useful?",
    "If you became a leader of a country, what would the press say about you?",
    "In your biography, which chapters would you ask your parents to skip?",

];
