export const questions = [
    "Why pigeons are government drones",
    "The secret purpose of pineapple on pizza",
    "Why the moon landing was staged by lizards",
    "How Wi-Fi signals control our thoughts",
    "The real reason cats are always watching us",
    "Why there are hidden messages in cereal box art",
    "How toothpaste companies secretly weaken our teeth",
    "The connection between socks disappearing in the dryer and aliens",
    "How crop circles are instructions for time travelers",
    "The real purpose behind artificial intelligence",
    "Why Bigfoot sightings correlate with tax season",
    "How lottery winners are part of a secret society",
    "Why the color blue was invented to control moods",
    "How coffee is a mind control serum",
    "The connection between rubber ducks and government surveillance",
    "Why clocks were designed to control time travelers",
    "How potatoes hold ancient knowledge",
    "Why airlines intentionally lose luggage",
    "How fast food mascots control human minds",
    "Why public libraries are secret mind-reading centers",
    "The connection between horoscopes and alien languages",
    "How bubble wrap was created to trap evil spirits",
    "Why emojis are ancient alien hieroglyphs",
    "The secret messages hidden in traffic signs",
    "How umbrellas are tools for mind control",
    "The real reason movie sequels exist",
    "Why sunglasses were designed to hide secrets",
    "How nail polish colors predict the future",
    "The real purpose of toe socks",
    "Why nature documentaries are coded government messages",
    "How the tooth fairy is a spy for the animal kingdom",
    "Why ice cream trucks are portals to other dimensions",
    "How instant noodles are a plot to control the youth",
    "Why jellybeans represent hidden political messages",
    "The connection between knitting and time travel",
    "How glitter is actually a tracking device",
    "Why video games are secretly historical reenactments",
    "How Bluetooth headphones connect to other dimensions",
    "Why birdsong is actually alien communication",
    "How vending machines spy on people",
    "Why clouds are holograms to cover UFOs",
    "The truth about disposable cutlery",
    "How garden gnomes protect us from unseen forces",
    "Why instant messaging was invented to study human emotions",
    "The connection between traffic lights and secret societies",
    "Why ballpoint pens hold ancient knowledge",
    "How shampoo companies secretly monitor our thoughts",
    "Why the color green is banned in some countries",
    "How board games prepare us for secret missions",
    "Why QR codes are encrypted maps",
    "How microwave ovens are tiny black holes",
    "Why public benches are listening devices",
    "The true purpose of string cheese",
    "How pigeons are the gatekeepers of the universe",
    "Why pocket lint holds the universe's secrets",
    "How cereal boxes predict world events",
    "The real reason why popcorn pops",
    "Why nail salons are intelligence outposts",
    "The connection between window blinds and covert operations",
    "How marshmallows were created to capture ghosts",
    "Why refrigerators are portals to parallel universes",
    "How high heels alter time perception",
    "The truth about rubber bands and their real purpose",
    "Why mirrors were originally intended as portals",
    "How light bulbs control human intelligence",
    "The secret behind peanut butter’s sticky power",
    "How couches are used to gather intel on relaxation",
    "Why spiders know too much about history",
    "How pine cones predict the weather",
    "Why zippers were invented by ancient alchemists",
    "The hidden purpose of chocolate chips",
    "How ice cream trucks secretly monitor neighborhoods",
    "The real origin of high-fives",
    "Why vacuum cleaners are actually data collectors",
    "How public fountains are portals to another realm",
    "The connection between denim jeans and mind control",
    "Why rubber erasers were created to erase memories",
    "The truth behind the shape of pretzels",
    "How fog is used for secret messages",
    "The real purpose behind amusement park roller coasters",
    "Why garden hoses may be watching us",
    "How hot sauce is a plot to desensitize taste buds",
    "The secret reason glitter never disappears",
    "How Wi-Fi passwords are coded messages",
    "Why house plants communicate with each other",
    "The connection between popcorn and psychic powers",
    "Why instant coffee is a government experiment",
    "How GPS directions are secretly psychological tests",
    "The truth behind shoelaces and their mysterious origins",
    "Why batteries go ‘missing’ in TV remotes",
    "How water bottles are secret energy sources",
    "The real reason alarm clocks exist",
    "Why yoga mats track fitness intelligence",
    "The secret messages in snowflakes",
    "Why bean bags were made to alter relaxation levels",
    "How chewing gum was created to influence thoughts",
    "Why movie popcorn tastes better than at-home popcorn",
    "The reason magnets stick to some people and not others",
    "How bicycles were invented to teach balance of the mind",
    "Why hoodies were designed for covert communication",
    "The real purpose of thumbtacks",
    "Why soap bubbles are used for inter-dimensional communication",
    "How napkins carry encrypted information",
    "Why tennis balls are used in alien research",
    "How cardboard boxes influence consumer behavior",
    "The hidden reason candles have unique scents",
    "Why cats are plotting to take over the internet",
    "The connection between headphones and mind reading",
    "How pillows contain hidden messages in the fabric",
    "Why soup spoons were invented to slow down eating",
    "The real purpose of shoeboxes",
    "How parking meters manipulate time",
    "Why lemonade was invented as a form of crowd control",
    "The true reason fire extinguishers are red",
    "Why balloons are used in secret experiments",
    "How keychains are actually tracking devices",
    "The hidden meanings behind post-it notes",
    "Why plastic straws were created to preserve secrets",
    "How pizza crust thickness affects brain function",
    "The real purpose of Christmas ornaments",
    "Why barcodes tell more than prices",
    "How salt and pepper shakers keep things balanced",
    "Why rollerblades were actually invented for spies",
    "The hidden meaning of the “power” button symbol",
    "How the shape of pasta influences personality",
    "Why juice boxes are used to control sugar levels",
    "The hidden purpose of soda bottle caps",
    "Why rainbows are actually ancient codes",
    "How video game controllers monitor emotions",
    "The real purpose of breakfast cereal",
    "Why license plates are numbered so specifically",
    "How bookmarks hold mysterious energy",
    "Why string lights are actually protection charms",
    "The connection between mustard and alien civilizations",
    "How aprons are made to hide secret pockets",
    "Why notebooks are designed to hold secrets",
    "The true purpose behind coloring books",
    "How fridge magnets attract hidden messages",
    "Why toasters are programmed to time travel",
    "The reason rice cookers are only used for rice",
    "Why sweaters are meant to keep secrets warm",
    "How water fountains hold hidden powers",
    "The secret mission of nightlights",
    "Why gym bags are perfectly sized for secrets",
    "How sleeping bags were invented to prevent wandering",
    "The connection between socks and parallel universes",
    "How bookmarks are tiny GPS devices",
    "The truth about the shape of ice cubes",
    "How wall clocks are used to control our pace",
    "Why mops have unique patterns on their handles",
    "How colored pencils are linked to aura reading"
];
