export const questions = [
    "Starry Night by Vincent van Gogh",
    "The Persistence of Memory by Salvador Dalí",
    "The Scream by Edvard Munch",
    "Mona Lisa by Leonardo da Vinci",
    "Girl with a Pearl Earring by Johannes Vermeer",
    "The Last Supper by Leonardo da Vinci",
    "The Birth of Venus by Sandro Botticelli",
    "The Creation of Adam by Michelangelo",
    "The Kiss by Gustav Klimt",
    "American Gothic by Grant Wood",
    "The School of Athens by Raphael",
    "Water Lilies by Claude Monet",
    "The Night Watch by Rembrandt",
    "Whistlejacket by George Stubbs",
    "The Girl with a Balloon by Banksy",
    "Guernica by Pablo Picasso",
    "Campbell's Soup Cans by Andy Warhol",
    "Nighthawks by Edward Hopper",
    "The Arnolfini Portrait by Jan van Eyck",
    "No. 5 by Jackson Pollock",
    "Self-Portrait with a Straw Hat by Élisabeth Louise Vigée Le Brun",
    "Las Meninas by Diego Velázquez",
    "The Great Wave off Kanagawa by Hokusai",
    "The Death of Socrates by Jacques-Louis David",
    "The Storm on the Sea of Galilee by Rembrandt",
    "The Hay Wain by John Constable",
    "Composition VIII by Wassily Kandinsky",
    "The Last Judgment by Michelangelo",
    "Fountain by Marcel Duchamp",
    "The Birth of the World by Joan Miró",
    "The Garden of Earthly Delights by Hieronymus Bosch",
    "Liberty Leading the People by Eugène Delacroix",
    "The Fighting Temeraire by J.M.W. Turner",
    "Portrait of a Lady by Gustav Klimt",
    "The Nut Gatherers by Jean-Baptiste-Siméon Chardin",
    "The Valley of Mexico from the Hillside of Santa Isabel by José María Velasco",
    "The Night Cafe by Vincent van Gogh",
    "Impression, Sunrise by Claude Monet",
    "The Lady of Shalott by John William Waterhouse",
    "Self-Portrait with Cropped Hair by Frida Kahlo",
    "The Red Studio by Henri Matisse",
    "The Mourners by Jean-Pierre de Cailhava",
    "The Two Fridas by Frida Kahlo",
    "The Birth of the Virgin by Pietro Lorenzetti",
    "The Last Judgment by Hans Memling",
    "A Sunday Afternoon on the Island of La Grande Jatte by Georges Seurat",
    "The Storm by Pierre-Auguste Cot",
    "The Dance Class by Edgar Degas",
    "The Dream by Henri Rousseau",
    "The Arnolfini Wedding by Jan van Eyck",
    "A Bar at the Folies-Bergère by Édouard Manet",
    "The Gleaners by Jean-François Millet",
    "The Kiss by Francesco Hayez",
    "Nocturne in Black and Gold: The Falling Rocket by James Whistler",
    "The Son of Man by René Magritte",
    "Portrait of Adele Bloch-Bauer I by Gustav Klimt",
    "The Fighting Temeraire by J.M.W. Turner",
    "The Oath of the Horatii by Jacques-Louis David",
    "The Death of Sardanapalus by Eugène Delacroix",
    "Wanderer above the Sea of Fog by Caspar David Friedrich",
    "Girl with a Mandolin by Pablo Picasso",
    "The Lady of Shallot by John William Waterhouse",
    "The Kiss by Gustav Klimt",
    "The Farm by Paul Gauguin",
    "The Night Watch by Rembrandt",
    "The Last Supper by Salvador Dalí",
    "Man at the Crossroads by Diego Rivera",
    "Study of a Woman by Pablo Picasso",
    "The Sleeping Gypsy by Henri Rousseau",
    "The Table by Juan Gris",
    "The Blue Boy by Thomas Gainsborough",
    "The Harvesters by Pieter Bruegel the Elder",
    "The Red Vineyard by Vincent van Gogh",
    "The Scream by Edvard Munch",
    "Woman with a Pearl Necklace in a Loge by Pierre-Auguste Renoir",
    "The Studio by Juan Gris",
    "The Garden of Love by Peter Paul Rubens",
    "The Night Watch by Rembrandt",
    "The Peasant Wedding by Pieter Bruegel the Elder",
    "The Last Supper by Leonardo da Vinci",
    "The Virgin of the Rocks by Leonardo da Vinci",
    "Self-Portrait with Bandaged Ear by Vincent van Gogh",
    "The School of Athens by Raphael",
    "The Night Watch by Rembrandt",
    "Composition with Red, Blue, and Yellow by Piet Mondrian",
    "The Art of Painting by Johannes Vermeer",
    "The Lovers by René Magritte",
    "The Kiss by Gustav Klimt",
    "The Creation of Eve by Michelangelo",
    "Portrait of a Young Woman by Giovanni Battista Moroni",
    "The Birth of Venus by Sandro Botticelli",
    "Portrait of a Lady by Gustav Klimt",
    "The Triumph of Death by Pieter Bruegel the Elder",
    "The Hay Wain by John Constable",
    "The Card Players by Paul Cézanne",
    "The Fighting Temeraire by J.M.W. Turner",
    "The Luncheon of the Boating Party by Pierre-Auguste Renoir",
    "Liberty Leading the People by Eugène Delacroix",
    "The Marriage of the Virgin by Raphael",
    "The Dance by Henri Matisse",
    "The Tower of Babel by Pieter Bruegel the Elder",
    "Portrait of Louis XIV by Hyacinthe Rigaud",
    "The Great Wave off Kanagawa by Hokusai",
    "The Birth of the World by Joan Miró",
    "The Mourners by Jean-Pierre de Cailhava",
    "American Gothic by Grant Wood",
    "The Balcony by Édouard Manet",
    "The Sleeping Venus by Giorgione",
    "The Old Guitarist by Pablo Picasso",
    "The Conspiracy of Claudius Civilis by Rembrandt",
    "The Kiss of the Sphinx by Jean-Auguste-Dominique Ingres",
    "A Wheatfield with Crows by Vincent van Gogh",
    "The Stone Breakers by Gustave Courbet",
    "The Grand Odalisque by Jean-Auguste-Dominique Ingres",
    "The Music Lesson by Johannes Vermeer",
    "The Young Martyr by Paul Delaroche",
    "The Two Fridas by Frida Kahlo",
    "The Rape of Europa by Paolo Veronese"
];
