export const questions = [
    "What's the most memorable adventure we've had together?",
    "If you could relive one moment from our friendship, what would it be?",
    "What's your favorite inside joke that we share?",
    "Which movie best represents our friendship?",
    "What's a skill or hobby you think I should try?",
    "What's one thing you've learned from our friendship?",
    "If we could go on a trip anywhere in the world, where would you want to go?",
    "What's your go-to song when you're in a great mood?",
    "What's a funny memory that always makes you laugh when you think about it?",
    "What's one thing you appreciate most about our friendship?",
    "What's one sign that you would probably stay friends with someone for life?",
    "What's the easiest way to break your trust?",
    "What's something about your life now that you would miss when you're eighty?",
    "Which day in your life do you wish you could erase from history?",
    "In what ways are you privileged?",
    "What's a common trait shared by everyone you've dated?",
    "Given the chance, what would your worst enemy want to tattoo on your back?",
    "What would your ten-year-old self think of your present self?",
    "If your life were a video game, which level would be the most difficult to get through?",
    "If you had to come up with a new class that everyone was required to take in school, what would it be?",
    "What's a character trait you hope you'd never pass down to your kids?",
    "What is one underrated quality you find attractive in a person?",
    "It's your final twenty-four hours on earth. You're in great shape and have unlimited funds. What do you do?",
    "How would you spend your time if you turned invisible for a week?",
    "When was the last time someone saw you cry?",
    "Have you ever felt differently about a person after you had dreamt about them?",
    "Who are the people most likely to thank you in their speech if they ever won an award?",
    "What's one thing your exes probably miss about you?",
    "Do you believe chemistry is inherent or is it something you can develop over time?",
    "When did you first learn about race and how did that change the way you saw people?",
    "If you could give your parents advice on how to raise you, what would you tell them?",
    "If all your exes got together, what's one complaint they would all agree on?"
];