export const questions = [
    "The impact of social media on mental health",
    "The science behind why cats purr",
    "How chocolate is made from bean to bar",
    "The history of the English language",
    "The process of photosynthesis in plants",
    "How the stock market works",
    "The importance of bees in the ecosystem",
    "The evolution of the smartphone",
    "The principles of quantum physics",
    "How vaccines are developed and tested",
    "The effects of climate change on polar bears",
    "The architecture of the Great Pyramids",
    "How music affects the brain",
    "The journey of water from rain to river",
    "The art of origami and its cultural significance",
    "The psychology of color in marketing",
    "The role of mitochondria in cellular energy",
    "How to brew the perfect cup of coffee",
    "The origins of the Olympic Games",
    "The mechanics of how airplanes fly",
    "The significance of the theory of relativity",
    "How the internet was created and evolved",
    "The anatomy of the human heart",
    "The process of making wine from grapes",
    "The impact of deforestation on wildlife",
    "How electric cars work and their benefits",
    "The history and significance of jazz music",
    "The process of human digestion",
    "How blockchain technology works",
    "The cultural impact of video games",
    "The significance of Shakespeare in literature",
    "How glaciers form and their impact on landscapes",
    "The role of government in public health",
    "The art of negotiation in business",
    "The principles of good design in architecture",
    "How the brain processes language",
    "The history and evolution of the Internet",
    "The impact of fast fashion on the environment",
    "How to identify different types of clouds",
    "The history of space exploration",
    "The principles of effective time management",
    "How to cultivate a successful garden",
    "The role of DNA in genetics",
    "The significance of ancient civilizations",
    "How sound waves travel and are perceived",
    "The importance of nutrition for overall health",
    "How renewable energy sources work",
    "The psychology behind advertising",
    "The history and impact of the printing press",
    "How to effectively manage stress",
    "The anatomy of a smartphone",
    "The significance of art in society",
    "How to analyze a piece of literature",
    "The impact of global warming on sea levels",
    "The history of aviation and its pioneers",
    "How to create a sustainable business model",
    "The art of storytelling in different cultures",
    "How human behavior is influenced by culture",
    "The significance of traditional medicine",
    "How to conduct scientific research",
    "The relationship between exercise and mental health",
    "The impact of urbanization on society",
    "How to improve your public speaking skills",
    "The science of sleep and its benefits",
    "How to understand basic economics",
    "The role of technology in education",
    "How to interpret body language",
    "The significance of wildlife conservation",
    "How to read and understand nutritional labels",
    "The basics of astronomy and celestial bodies",
    "How to develop a healthy work-life balance",
    "The evolution of transportation methods",
    "The importance of critical thinking skills",
    "How to prepare for a natural disaster",
    "The significance of emotional intelligence",
    "How to write a compelling resume",
    "The impact of diet on physical performance",
    "The mechanics of gravity and its effects",
    "The role of hormones in human behavior",
    "How to practice mindfulness effectively",
    "The history and evolution of dance styles",
    "How climate influences architectural design",
    "The significance of cultural heritage sites",
    "How artificial intelligence is transforming industries",
    "The basics of cryptocurrency and its uses",
    "How to conduct a successful job interview",
    "The science behind optical illusions",
    "The history of the feminist movement",
    "How to understand the principles of physics",
    "The importance of sleep for cognitive function",
    "How to build effective communication skills",
    "The anatomy of a computer and how it works",
    "The significance of renewable resources",
    "How art influences social change",
    "The basics of legal systems and their functions",
    "How climate change affects agriculture",
    "The role of etiquette in professional settings",
    "The science behind addiction and recovery",
    "The impact of global trade on economies",
    "How to analyze market trends",
    "The history of medicine and major breakthroughs",
    "How social movements change public policy",
    "The mechanics of how the eye perceives images",
    "How to manage personal finances effectively",
    "The evolution of musical instruments",
    "The importance of mental health awareness",
    "How to create effective marketing strategies",
    "The science of animal behavior and instincts",
    "The role of technology in modern relationships",
    "How the body processes different types of nutrients",
    "The history and significance of world religions",
    "How to build resilience in challenging times",
    "The basics of web development and design",
    "How to interpret historical documents",
    "The significance of empathy in human interactions",
    "How to assess the credibility of sources",
    "The evolution of transportation technologies",
    "How to navigate personal and professional conflicts",
    "The impact of pollution on public health",
    "How to write a compelling story",
    "The basics of climate science",
    "How fashion reflects cultural identity",
    "The significance of volunteerism in communities",
    "How to develop a successful business plan",
    "The role of the arts in education",
    "How to improve productivity in the workplace",
    "The impact of social media on political movements",
    "How to study effectively for exams",
    "The basics of ethical decision-making",
    "How to prepare healthy meals on a budget",
    "The science of happiness and well-being",
    "How to foster creativity in children",
    "The role of language in shaping thought",
    "How to create a positive workplace culture",
    "The impact of technological advancements on society",
    "How to conduct a scientific experiment",
    "The importance of environmental stewardship"
];
